# Generated by Django 5.2.4 on 2025-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
