# Generated by Django 5.2.4 on 2025-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_gameimage_image_alter_gameimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevideo',
            name='is_main_video',
            field=models.BooleanField(default=False),
        ),
    ]
