# Generated by Django 5.2.4 on 2025-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamevideo_is_main_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevideo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
